---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: <database-name>-ingress
  namespace: <organization-name>
spec:
  rules:
  - host: "<database-name>.<organization-name>.ahti.io"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: <database-name>-db-service
            port:
              number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: <database-name>-db-service
  namespace: <organization-name>
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: <database-name>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: <database-name>
  namespace: <organization-name>
  labels:
    name: <database-name>
spec:
  replicas: 1
  selector:
    matchLabels:
      name: <database-name>
  template:
    metadata:
      labels:
        name: <database-name>
    spec:
      containers:
        - name: <database-name>
          image: "ghcr.io/tursodatabase/libsql-server:latest"
          imagePullPolicy: "Always"
          ports:
          - containerPort: 8080
          env:
            - name: SQLD_NODE
              value: "primary"
          resources:
            requests:
              cpu: 500m
              memory: 256Mi
            limits:
              cpu: 1
              memory: 512Mi
